/* Generated By:JavaCC: Do not edit this line. ScannerConstants.java */
package gm.utg.fw.scanner;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ScannerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT = 5;
  /** RegularExpression Id. */
  int ID = 6;
  /** RegularExpression Id. */
  int NUM = 7;
  /** RegularExpression Id. */
  int NEQ = 8;
  /** RegularExpression Id. */
  int SET = 9;
  /** RegularExpression Id. */
  int PLUS = 10;
  /** RegularExpression Id. */
  int MINUS = 11;
  /** RegularExpression Id. */
  int END = 12;
  /** RegularExpression Id. */
  int WHILE = 13;
  /** RegularExpression Id. */
  int FOR = 14;
  /** RegularExpression Id. */
  int DO = 15;
  /** RegularExpression Id. */
  int OD = 16;
  /** RegularExpression Id. */
  int QUIT = 17;
  /** RegularExpression Id. */
  int FUNC = 18;
  /** RegularExpression Id. */
  int LPAR = 19;
  /** RegularExpression Id. */
  int RPAR = 20;
  /** RegularExpression Id. */
  int COMMA = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<COMMENT>",
    "<ID>",
    "<NUM>",
    "\"!=\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\";\"",
    "\"while\"",
    "\"for\"",
    "\"do\"",
    "\"od\"",
    "\"quit\"",
    "<FUNC>",
    "\"(\"",
    "\")\"",
    "\",\"",
  };

}
